[workspace]
resolver = "2"
members = [
    "crates/*",
]
default-members = [
    "crates/*",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
arrayvec = "0.7"
clap = { version = "4.5", features = ["derive"] }
criterion = "0.5"
either = "1.0"
gc-arena = { git = "https://github.com/kyren/gc-arena", rev = "d651e3b4363d525a2d502c2305bc73e291835c84" }
serde = "1.0"
thiserror = "2.0"

fabricator-compiler.path = "crates/compiler"
fabricator-util.path = "crates/util"
fabricator-vm.path = "crates/vm"
fabricator-yy-format.path = "crates/yy-format"

