[package]
name = "fabricator-stdlib"
version.workspace = true
edition.workspace = true

[dependencies]
gc-arena.workspace = true
thiserror.workspace = true
serde_json.workspace = true

fabricator-vm.workspace = true
