[package]
name = "fabricator-collision"
version.workspace = true
edition.workspace = true

[dependencies]
arrayvec.workspace = true
either.workspace = true
num.workspace = true
rand.workspace = true
thiserror.workspace = true

fabricator-math.workspace = true
