[package]
name = "fabricator-vm"
version.workspace = true
edition.workspace = true

[dependencies]
gc-arena.workspace = true
thiserror.workspace = true
rustc-hash = "2.0"

fabricator-util.workspace = true
